FROM golang:alpine

# https://mirrors.alpinelinux.org/
RUN sed -i 's@dl-cdn.alpinelinux.org@ftp.halifax.rwth-aachen.de@g' /etc/apk/repositories

RUN apk update
RUN apk upgrade

# required CGO compile
RUN apk add --no-cache \
  curl git gcc make linux-headers \
  musl-dev bash patch pkgconfig xz \
  sqlite-static sqlite-dev yarn typescript npm

ENV XZ_OPT=-e9
COPY build-static-golang-2.sh build-static-golang-2.sh
RUN chmod +x ./build-static-golang-2.sh
RUN bash ./build-static-golang-2.sh
